### PR TITLE
re-enable classic midimapper and add support for NRPNs

### PR DESCRIPTION
**Pull request by friedolino78**
(needed for large amounts of controllers)

### CODE REVIEW

**Comment by friedolino78** [comment]
what's new are ports to map controls via OSC
oscsend localhost 7777 /midi-map-cc is 91  /part0/kit0/adpars/GlobalPar/AmpEnvelope/A_dt
oscsend localhost 7777 /midi-map-cc iis 92 3 /part0/kit0/adpars/GlobalPar/AmpEnvelope/D_dt
oscsend localhost 7777 /midi-map-nrpn iis 12345 1 /part0/kit0/adpars/GlobalPar/AmpEnvelope/R_dt

**Comment by fundamental** [comment]
FYI, this is currently failing the CI build (build failure before tests could even be run). Were there changes on the rtosc and zyn side to get the code working?

**Comment by friedolino78** [comment]
> FYI, this is currently failing the CI build (build failure before tests could even be run). Were there changes on the rtosc and zyn side to get the code working?

you are right. I did some changes in rtosc.

**Comment by friedolino78** [comment]
from my side everything seems to be fine now. ready for review&merge

**Comment by fundamental** [comment]
So, reviewing this it looks like it doesn't conflict with automations at all, but it doesn't look like it actually does anything either. Shouldn't there be a hook in setController()?

**Comment by friedolino78** [comment]
> So, reviewing this it looks like it doesn't conflict with automations at all, but it doesn't look like it actually does anything either. Shouldn't there be a hook in setController()?

that would be strange since I used it successfully ;-)

there is:
midi.handleCC(type, par, chan, false); 
for CCs and
midi.handleCC(parhi<<7&parlo,valhi<<7&vallo, chan, true);
for NRPNs.

**Comment by fundamental** [comment]
Ah, yep, my bad. I really wish github's diff featured some better semantic information as I just misread it. Merged.

**Pull request merged**
