### PR TITLE
Add more details in TODO-release.md

### PR DESCRIPTION
**Pull request by pgervais**

### CODE REVIEW

**Comment by pgervais** [comment]
This is an attempt at making the release checklist more detailed to reduce friction for people like me who lack some context.

**Comment by fundamental** [comment]
One detail lost in translation is updating the news on the website is referring to this page: https://zynaddsubfx.sourceforge.io/news.html It's not directly linked in the nav bar, but it is still reachable. Otherwise I generally agree with the clarifications.

**Comment by pgervais** [comment]
I added a reference to the URL you mentioned. Thanks a lot for the review!

**Comment by fundamental** [comment]
Thanks for the doc improvements :+1:

**Pull request merged**
