### PR TITLE
fixed misspelling of "distortion"

### PR DESCRIPTION
**Pull request by dancesWithBugs**

### CODE REVIEW

**Comment by fundamental** [comment]
Looks reasonable, though it does require a OSC metadata regeneration as it renames part of the port hierarchy. I'll circle back to this to make sure that I don't forget about that side of the merge.

**Comment by fundamental** [comment]
Actually, since it's more than just an osc schema update (i.e. the path change in the distortion effect UI), would you be interested in having a matching pull request on https://github.com/mruby-zest/mruby-zest-build ?

**Comment by dancesWithBugs** [comment]
Hope it works https://github.com/mruby-zest/mruby-zest-build/pull/79

**Comment by fundamental** [comment]
All changes check out fine in testing. Thanks for the fix. :+1:

**Pull request merged**
