### PR TITLE
Sndio: Fix always true conditionals

### PR DESCRIPTION
**Pull request by JohannesLorenz**

### CODE REVIEW

**Comment by fundamental** [comment]
Interesting that the man page isn't more explicit about the return code. The interpretation appears to be right based upon me reading between the lines, though I didn't look at the examples, just the man page.

**Comment by JohannesLorenz** [comment]
Let's merge this then? Or should we make tests?

**Comment by kinichiro** [comment]
sio_write and mio_read return size_t value and it never could be negative.
I think this PR is fine.

**Comment by JohannesLorenz** [comment]
I just did a few tests with sndio, and it all worked. Time to merge this.

**Pull request merged**
