### PR TITLE
Sympathetic: Make "Generic" a preset

### PR DESCRIPTION
**Pull request by JohannesLorenz**
As discussed on Discord.

### CODE REVIEW

**Comment by friedolino78** [comment]
I am not quite sure anymore about the idea to make "generic" a preset.
Maybe we should think again about the preset handling in general.
My idea is that i can choose a preset to have the params set. If I change a value, it is no more the preset. But the gui still shows the preset name. Therefor I wanted to have a way to say "no preset". Making this "no preset" a preset gives me a bit of logical discomfort.

**Comment by JohannesLorenz** [comment]
You mean you want the GUI to always display "no preset" as soon as you changed a parameter? Then this could be a GUI-only fix.

One reason to still display the preset might be "It's still a Hall reverb, just maybe with 1 or 2 changed parameters" - if the preset is not displayed anymore, the user won't know if it's a Room/Hall/Tunnel reverb.

One compromise could also be to just let the GUI gray-out the preset as soon as one parameter is changed. Or display all derivating parameters (which could be done since we know the default values for each preset).

**Comment by fundamental** [comment]
Shifting how presets are shown sounds interesting. It might be a bit of a messy implementation, but I'd expect users would like it. Per the code, making updates only on parameter differences sounds good to me. Were the removal of some of the rDefault() statements intentional?

**Comment by JohannesLorenz** [comment]
> Per the code, making updates only on parameter differences sounds good to me.

Which kind of updates do you mean?

> Were the removal of some of the rDefault() statements intentional?

Yes. The idea was that the presets have different default values for those ports, so there is no "one default" value that matches "most of the presets except a few".

**Comment by fundamental** [comment]
> Which kind of updates ...

These updates:
```
            if(Punison_frequency_spread != value)
```

**Review by friedolino78 — APPROVED** [review]
looks good to me

**Pull request merged**
