### PR TITLE
[skip ci] Implement ZynAddSubFX::getDescription

### PR DESCRIPTION
**Pull request by JohannesLorenz**
This is mostly what wikipedia/our README/our website say. Feel free to improve.

### CODE REVIEW

**Comment by fundamental** [comment]
Is that a typical length for one of those descriptions?
I would expect the goal of the text to be to differentiate the plugin from others. Perhaps some note about having three synthesis engines + built in effects or some other aspect of the functionality uncommon to other synths?

**Comment by falkTX** [comment]
That seems like a generic description that really doesnt say anything in particular about the plugin in question.
For comparison https://github.com/DISTRHO/Nekobi/blob/master/plugins/Nekobi/DistrhoPluginNekobi.hpp#L63

**Comment by JohannesLorenz** [comment]
Oh, right: `./distrho/DistrhoPlugin.hpp` says "Get an extensive comment/description about the plugin". Sorry, I'll fix this later.

**Comment by JohannesLorenz** [comment]
New proposal: "A free, open-source software synthesizer *featuring additive, subtractive and Fourier synthes methods, modulators for amplitude, frequency and filters with powerful oscillators and envelopes, and a variety of built-in effects.*"

Does this make sense? Should it be split into multiple sentences?

**Comment by fundamental** [comment]
I'd truncate that to "Synthesizer featuring additive, subtractive, and Fourier synthesis methods, a variety of modulators, powerful oscillator editors, and a variety of built-in effects." That puts it somewhat closer to the nekobi example.

**Comment by JohannesLorenz** [comment]
I pushed your proposal without changes, I think it's very good.

Ready to merge (from my side).

**Comment by fundamental** [comment]
Works for me.

**Pull request merged**
