### PR TITLE
keep ENV knobs in sync in free mode

### PR DESCRIPTION
**Pull request by friedolino78**
this has the advantage that the ADSR ports can be still used in freemode. use case especially ADSR controls via midi CC.

### CODE REVIEW

**Comment by fundamental** [comment]
This PR is still marked as a draft/WIP. Is that still the case?

**Comment by friedolino78** [comment]
> This PR is still marked as a draft/WIP. Is that still the case?

no, just forgot to switch it back

**Comment by friedolino78** [comment]
> Code looks right, but to avoid a possible crash:
> Is it possible for Penvpoints-1 or Penvsustain-1 to become negative values at any point? I know in non-free mode you should be safe, but in free mode you can delete a lot of points which might make it possible for one of those member variables to be zero. If it's safe, let me know and this is good to merge

it's safe. 

Penvpoints is only decremented in line 291. But if it's <=3 the code cannot be reached.
because of line 283:
`        if(curpoint<1 || curpoint>=env->Penvpoints-1 || env->Penvpoints<=3)
            return;`

**Comment by fundamental** [comment]
Thanks for the confirmation

**Pull request merged**
