### PR TITLE
optimize interpolation in Chorus

### PR DESCRIPTION
**Pull request by friedolino78**
optimize interpolations in Chorus

### CODE REVIEW

**Comment by fundamental** [comment]
I agree with the diff in Util.cpp, the diff in Chorus.cpp conflicts with zyn's known behavior from before I was involved in the project. So either we've always had a wrong chorus or this change makes chorus incorrect. I'm pretty sure I can see a clear difference in the two Chorus.cpp files using baudline before/after. So, if the Util.cpp changes is a commit that is 100% ready to go, the other one needs some evidence of that being the correct way to implement a chorus effect IMO.

**Comment by friedolino78** [comment]
Util part has moved to:
https://github.com/zynaddsubfx/zynaddsubfx/pull/291

**Comment by friedolino78** [comment]
> So either we've always had a wrong chorus or this change makes chorus incorrect. I'm pretty sure I can see a clear difference in the two Chorus.cpp files using baudline before/after. So, if the Util.cpp changes is a commit that is 100% ready to go, the other one needs some evidence of that being the correct way to implement a chorus effect IMO.

I would think that the result is mathematically the same. But we can simply inverstigate it further by having both implementations on left vs right channel.

**Comment by fundamental** [comment]
Based on additional discussion elsewhere it sounds like the left/right experiment showed that this PR was different and I think the commit here is still prior to the fix which makes the two versions equivalent.

**Comment by friedolino78** [comment]
unneeded. it's part of the Ensemble PR

**Comment by friedolino78** [comment]
this PR isn't needed as it is part of the Ensemble PR

**Pull request closed without merging**
