### PR TITLE
convert subpar/ampvelocityscale to float

### PR DESCRIPTION
**Pull request by michiboo**
Hi I convert amp velocity scale function to float in subpar!

### CODE REVIEW

**Comment by fundamental** [comment]
It looks like this PR is missing the ability to load older versions of the ampvelocityscale parameter to maintain compatibility with older .xmz files.

**Comment by michiboo** [comment]
Hi changes are made as requested!

**Comment by fundamental** [comment]
Based upon the newer commit, it looks like the test file (guitar-adnote.xmz) was incorrectly updated. If it was previously at 90 (0..127), then it should have mapped to ~70.86 instead of staying at 90.

**Comment by michiboo** [comment]
I am little bit confused as you told me before in test file it can contain different value other than default? Anyhow I will change it to 70.8 in testfile!

**Comment by michiboo** [comment]
Hi, I have made changes as requested!

**Comment by fundamental** [comment]
Everything is looking good to me. @dsheeler you don't see anything that I'm overlooking, right?

**Comment by dsheeler** [comment]
@fundamental: looks good to me, too.

**Pull request merged**
