### PR TITLE
change padpar parameter

### PR DESCRIPTION
**Pull request by dhruveshk**

### CODE REVIEW

**Comment by fundamental** [comment]
Current commits do not compile due to an incorrect macro name (I think it's rDoc, not rdoc). The tests cannot be run, but I do expect at least one test to fail once the compilation bug is fixed (PluginTest).
The version check would not be against 3.0.3 any more since there have been subsequent releases.

**Comment by fundamental** [comment]
Additionally, it would be great to incorporate the 4* into the dB mapping, adding an offset of +12.0411 dB into the current -60..0 dB range.

**Comment by dhruveshk** [comment]
> Additionally, it would be great to incorporate the 4* into the dB mapping, adding an offset of +12.0411 dB into the current -60..0 dB range.
ok, will be doing it

**Comment by fundamental** [comment]
Bump

**Pull request closed without merging**
