### PR TITLE
Bugfix: Removes occurences to HISTORY.txt

### PR DESCRIPTION
**Pull request by hickscorp**
The build currently fails because of a missing file at the root of the build tree. This PR fixes it.

### CODE REVIEW

**Comment by jofemodo** [comment]
I've tested and the problem really exists (make install fails!!) and it gets solved with this PR.

**Comment by Jacalz** [comment]
I'm sorry this is my fault. I didn't know that the file was mentioned in that file.

**Comment by fundamental** [comment]
Thanks for the fix :+1:

**Comment by hselasky** [comment]
Hi I see that the sourceforge tarball has a HISTORY.txt file should this be installed?

Looks like someone has to resolve this merge conflict:

https://sourceforge.net/p/zynaddsubfx/code/ci/98e0b77a1a543252307dffb4a32abb2f852c8618

--HPS

**Comment by fundamental** [comment]
On 10-03, HPS wrote:
> Hi I see that the sourceforge tarball has a HISTORY.txt file should this be installed?

Previous versions used the HISTORY.txt file, though it seems that going
forward one would not be used.
I've resolved the merge conflict running under that assumption.

**Pull request merged**
